# pre-commit configuration file and specification of the hooks it uses
#
# HOOKS:
# - commitlint: Verify that commit message meets rules
#               specified in commitlint.config.js file
# - trailing-whitespace: Delete trailing whitespaces
# - black: Python code formatter
# - flake8: Check code base against coding style (PEP8),
#           programming errors (like “library imported but unused” and “Undefined name”)
#           and to check cyclomatic complexity
# - mypy: Static type checker for Python.

default_stages: [commit]

repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v8.0.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
    additional_dependencies: ['@commitlint/config-conventional']

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--line-length=100]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--max-line-length=100]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.940
    hooks:
    -   id: mypy
