# Docker compose configuration file
#
# SERVICES:
# - db: PostgreSQL database
# - pgadmin: Web administration interface of PostgreSQL database
# - web: Web application (moliuWeb) powered by Django
# - nginx: Nginx web server used in production environment

version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmindata:/var/lib/pgadmin
    ports:
      - "8101:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

  web:
    build: .
    image: moliuweb
    volumes:
      - webstaticdata:/app/static
      - webmediadata:/app/media
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - webstaticdata:/nginx/static
      - webmediadata:/nginx/media
    ports:
      - "8100:8000"
    depends_on:
      - web
    restart: always

volumes:
  pgdata:
  pgadmindata:
  webstaticdata:
  webmediadata: