version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmindata:/var/lib/pgadmin
    ports:
      - "8101:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    restart: always

  web:
    build: .
    image: moliuweb
    volumes:
      - webdata:/app/media
    ports:
      - "8100:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
  pgadmindata:
  webdata: