# Generated by Django 4.0.2 on 2022-04-03 18:03

from django.db import migrations, models
import django.db.models.deletion
import moliuWeb.models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[str] = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("learningTechnique", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("surnames", models.CharField(max_length=70, null=True)),
                ("nickname", models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("video", models.FileField(upload_to="gamesVideos/")),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=models.SET(moliuWeb.models.getSentinelActivity),
                        to="moliuWeb.activity",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="moliuWeb.model",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=models.SET(moliuWeb.models.getSentinelPatient),
                        to="moliuWeb.patient",
                    ),
                ),
            ],
        ),
    ]
