# Generated by Django 4.0.2 on 2022-04-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moliuWeb", "0003_posture_delete_frame"),
    ]

    operations = [
        migrations.AddField(
            model_name="posture",
            name="isClassified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="posture",
            name="score",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Very Bad"),
                    (25, "Bad"),
                    (50, "Regular"),
                    (75, "Good"),
                    (100, "Very Good"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
