# Generated by Django 4.0.2 on 2022-04-28 09:29

from django.db import migrations


def addPatient0(apps, schema_editor):
    Patient = apps.get_model("moliuWeb", "Patient")
    p = Patient(name="paciente0")
    p.save()


def removePatient0(apps, schema_editor):
    Patient = apps.get_model("moliuWeb", "Patient")
    p = Patient.objects.get(pk=1, name="paciente0")
    p.delete()


def addActivity0(apps, schema_editor):
    Activity = apps.get_model("moliuWeb", "Activity")
    a = Activity(name="actividad0")
    a.save()


def removeActivity0(apps, schema_editor):
    Activity = apps.get_model("moliuWeb", "Activity")
    a = Activity.objects.get(pk=1, name="actividad0")
    a.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("moliuWeb", "0005_rename_isclassified_posture_isscored"),
    ]

    operations = [
        migrations.RunPython(addPatient0, removePatient0),
        migrations.RunPython(addActivity0, removeActivity0),
    ]
