# Generated by Django 4.0.2 on 2022-08-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moliuWeb", "0008_alter_patient_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="background",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="points",
            field=models.JSONField(null=True),
        ),
    ]
