# Generated by Django 4.0.2 on 2022-08-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moliuWeb", "0009_activity_background_activity_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="music",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
