# Generated by Django 4.0.2 on 2022-04-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moliuWeb", "0004_posture_isclassified_alter_posture_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posture",
            old_name="isClassified",
            new_name="isScored",
        ),
    ]
