# Generated by Django 4.0.2 on 2022-06-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moliuWeb", "0007_game_joints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="nickname",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
