# Generated by Django 4.0.2 on 2022-08-25 19:39

from django.db import migrations, models
import moliuWeb.storage


class Migration(migrations.Migration):

    dependencies = [
        ("moliuWeb", "0009_activity_background_activity_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="background",
            field=models.FileField(
                null=True,
                storage=moliuWeb.storage.MyFileStorage(),
                upload_to="activities/backgrounds/",
            ),
        ),
    ]
