# Generated by Django 4.0.2 on 2022-08-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moliuWeb", "0010_alter_activity_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="music",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="background",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
