# Generated by Django 4.0.2 on 2022-09-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moliuWeb", "0010_activity_music"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="name",
            field=models.CharField(default="Un modelo", max_length=255),
        ),
        migrations.AlterField(
            model_name="model",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="model",
            name="filename",
            field=models.FileField(upload_to="models/"),
        ),
    ]
