# Generated by Django 4.0.2 on 2022-09-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moliuWeb", "0011_model_name_alter_model_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="model",
        ),
    ]
