# Generated by Django 4.0.2 on 2022-09-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moliuWeb", "0012_remove_game_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="model",
            name="name",
            field=models.CharField(default="Un modelo", max_length=255, unique=True),
        ),
    ]
